### PR TITLE
Use resource graph for Subscription lookup

### PR DESCRIPTION
**Pull request by krowlandson**
<h2 id=overviewsummary>Overview/Summary </h2>
<p>Currently the ALZ Accelerator subscription selection fields don't always display the subscriptions a customer is looking to select. The issue we are facing is that when a customer has a large number of subscriptions (greater than 50), the REST API for <code>/subscriptions?api-version=2020-01-01</code> paginates the response so not all subscriptions can be obtained by the <a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/microsoft-solutions-armapicontrol">Microsoft.Solution.ArmApiControl</a> UI element. </p>
<p>This PR updates all subscription selection fields to use the Azure Resource Graph API that will add many benefits over the current <a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/microsoft-solutions-armapicontrol">Microsoft.Solution.ArmApiControl</a> UI element, including: </p>
<ul>
<li>Ability to return up to 1,000 subscriptions in the result (with cancelled subscriptions excluded from the results) </li>
<li>Ability to display both the name and subscription ID in the dropdown </li>
<li>Ability to filter results </li>
<li>Ability to support multiple selection where needed </li>
</ul>
<h2 id=thisprfixesaddschangesremoves>This PR fixes/adds/changes/removes </h2>
<ol>
<li>Feedback request to improve Subscription selection experience (internally tracked) </li>
</ol>
<h3 id=breakingchanges>Breaking Changes </h3>
<p>n/a </p>
<h2 id=testingevidence>Testing Evidence </h2>
<p>Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate). </p>
<h3 id=testingurls>Testing URLs </h3>
<h4 id=azurepublic>Azure Public </h4>
<p><a href="https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https:%2f%2fraw.githubusercontent.com%2fkrowlandson%2fEnterprise-Scale%2fUseResourceGraph%2feslzArm%2feslzArm.json/uiFormDefinitionUri/https:%2f%2fraw.githubusercontent.com%2fkrowlandson%2fEnterprise-Scale%2fUseResourceGraph%2feslzArm%2feslz-portal.json">Deploy To Azure</a> </p>
<h4 id=azureusgovfairfax>Azure US Gov (Fairfax) </h4>
<p><a href="https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https:%2f%2fraw.githubusercontent.com%2fkrowlandson%2fEnterprise-Scale%2fUseResourceGraph%2feslzArm%2feslzArm.json/uiFormDefinitionUri/https:%2f%2fraw.githubusercontent.com%2fkrowlandson%2fEnterprise-Scale%2fUseResourceGraph%2feslzArm%2feslz-portal.json">Deploy To Azure</a> </p>
<h2 id=aspartofthispullrequestihave>As part of this Pull Request I have </h2>
<ul>
<li>[x] Checked for duplicate <a href="https://github.com/Azure/Enterprise-Scale/pulls">Pull Requests</a> </li>
<li>[x] Associated it with relevant <a href="https://github.com/Azure/Enterprise-Scale/issues">issues</a>, for tracking and closure. </li>
<li>[x] Ensured my code/branch is up-to-date with the latest changes in the <code>main</code> <a href="https://github.com/Azure/Enterprise-Scale/tree/main">branch</a> </li>
<li>[x] Performed testing and provided evidence. </li>
<li>[x] Updated relevant and associated documentation. </li>
<li>[x] Updated the <a href="https://github.com/Azure/Enterprise-Scale/wiki/Whats-new">&quot;What's New?&quot;</a> wiki page (located: <code>/docs/wiki/whats-new.md</code>) </li>
</ul>

### CODE REVIEW

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Looks good.

Do we need to update this too? https://github.com/Azure/Enterprise-Scale/wiki/FAQ#the-enterprise-scale-also-known-as-the-azure-landing-zone-accelerator-portal-based-deployment-doesnt-display-all-subscriptions-in-the-drop-down-lists

**Comment by jtracey93** [comment]
@msftbot don't allow this PR to be merged until @JefferyMitchell has approved

**Comment by JefferyMitchell** [comment]
@jtracey93 @krowlandson Updated the FAQ here - https://github.com/Azure/Enterprise-Scale/wiki/FAQ#the-azure-landing-zone-portal-accelerator-also-known-as-enterprise-scale-landing-zone-deployment-doesnt-display-all-subscriptions-in-the-drop-down-lists

**Review by jtracey93 — CHANGES_REQUESTED** [review]
image
Bug found by @JefferyMitchell and myself. Default options + Hub & Spoke 3rd party NVA

**Comment by JefferyMitchell** [comment]
Raw Error Summary:
 {
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: 'The deployment metadata 'SUBSCRIPTION' is not valid.'."
}

**Review by jtracey93 — DISMISSED** [review]

**Comment by krowlandson** [comment]
Including increase to default value of `delayCount` from `10` to `30` to improve reliability.

This was previously causing pipeline runs to take too long to complete, but recent observations suggest that this now runs through much quicker again and is resulting in regular `out of scope` errors when creating Policy Assignments,

image showing the preparingToLaunch deployments occurring within a short timeframe

**Review by jtracey93 — APPROVED** [review]

**Pull request merged**
