### PR TITLE
Validate VPN/ER Gateway Subnet CIDR Range

### PR DESCRIPTION
**Pull request by marvinbuss**
## Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. Fixes https://github.com/Azure/Enterprise-Scale/issues/779

### Breaking Changes

1. No breaking changes

## Testing Evidence

image

image

image

image

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by marvinbuss** [comment]
@victorar & @daltondhcp Please give this a test. 👍

**Review by daltondhcp — APPROVED** [review]
LGTM

**Comment by victorar** [comment]
This looks great, thanks Marvin!

image

image

**Review by victorar — APPROVED** [review]
LGTM

**Pull request merged**
