### PR TITLE
Wiki user guide updates

### PR DESCRIPTION
**Pull request by JefferyMitchell**
<h2 id=overviewsummary>Overview/Summary </h2>
<p>Updates to UI changes screenshots and 
Replace this with a brief description of what this Pull Request fixes, changes, etc. </p>
<h2 id=thisprfixesaddschangesremoves>This PR fixes/adds/changes/removes </h2>
<ol>
<li>Update screen shots and UI for Wiki deployment guides </li>
<li>Prep updates accelerator versions and reduce portal experience naming in screenshots </li>
</ol>

### CODE REVIEW

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Hey @JefferyMitchell can you please add some brief update notes to the what's new page in the wiki so folles can get a quick update on what is being done here. 

Also I see you've added and renamed a few docs but not updated the navigation menus on the main README.md file, the wiki home page or the wiki sidebar. Could these get updated also please in this PR?

**Review by krowlandson — CHANGES_REQUESTED** [review]
Further to Jack's comments, some much needed updates and great to see the ALZ rebranding coming further into our docs... thank you!

Where you are creating effectively duplicate pages (so as not to break links to old content), can you please update the old pages to reference the new ones via a link rather than with duplicate content?

I am proposing using the following format in an update I'm currently working on:

```markdown
# This page has moved

Please refer to [< PAGE_TITLE >](< PAGE_LINK>)

```

If we all agree on this, would be good to implement consistently.

**Review by krowlandson — APPROVED** [review]
LGTM 👍🏻

**Review by jtracey93 — APPROVED** [review]

**Comment by jtracey93** [comment]
@JefferyMitchell @krowlandson is this good to merge?

**Comment by krowlandson** [comment]
> @JefferyMitchell @krowlandson is this good to merge?

Yup, good from my side @jtracey93

**Review by mblant — APPROVED** [review]
Looks good.

**Comment by paulgrimley** [comment]
Welcome updates and refresh @JefferyMitchell!

**Comment by JefferyMitchell** [comment]
@jtracey93 @krowlandson All reviews complete.

**Pull request merged**
