### PR TITLE
Add  the hint to register the resource provider Microsoft.Management before deployment

### PR DESCRIPTION
**Pull request by nielsophey**
**This PR fixes**

### CODE REVIEW

**Comment by uday31in** [comment]
@nielsophey - what is the issue you are encountering?

CC: @krnese

**Comment by krnese** [comment]
RP registration is done implicitly when deploying ARM templates including resources for a given namespace. What is the issue?

**Comment by nielsophey** [comment]
Hi If you deploy the ARM template without having the Resource provider registered you will get an Error...I have tried it out twice in different subscriptions. If Microsoft.Management is not registered the deployment will not run - so my idea was to write it into the prereqs...

**Comment by krnese** [comment]
@nielsophey thanks for adding details. Can you pls share repro steps, and point to template you deployed, how you deployed, as well as your permissions on the tenant root? The template will register management RP (to the tenant) when creating the management group structure.

**Comment by nielsophey** [comment]
@krnese - i took the template https://ms.portal.azure.com/?feature.customportal=false#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzOps%2Fmain%2Ftemplate%2Fux-foundation.json and startet to deploy it into a quite new tenant without ever having a management group deployed. The tenant had only one subscription. The deployment starter and failed because Microsoft.Management resource prodiver was not found - once I registered the RP the deployment worked (still having the trouble to do the deployment twice, some policies needed time to be deployed). Can I share something else to you to make it more clear?

**Comment by krnese** [comment]
@nielsophey; we have verified that this is not by design and we are investigating with the team what is occasionally causing this.

**Pull request closed without merging**
