### PR TITLE
Deprecate custom policy - Deploy SQL DB TDE

### PR DESCRIPTION
**Pull request by Springstone**
## Overview/Summary

Deprecating custom policy `Deploy SQL Database Transparent Data Encryption` as there is a working built-in [Deploy SQL DB transparent data encryption](https://www.azadvertizer.net/azpolicyadvertizer/86a912f6-9a06-4e26-b447-11b16ba8659f.html)

## This PR fixes/adds/changes/removes

1. Deprecating custom policy `Deploy SQL Database Transparent Data Encryption`

### Breaking Changes

1. N/A

## Testing Evidence

N/A

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [X] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [X] Performed testing and provided evidence.
- [X] Ensured [contribution guidance](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide) is followed.
- [X] Updated relevant and associated documentation.
- [X] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Need to update the initiative [Deploy-Sql-Security](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Deploy-Sql-Security.html) also

**Comment by Springstone** [comment]
> Need to update the initiative [Deploy-Sql-Security](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Deploy-Sql-Security.html) also

Totally missed this and wasn't aware of the assignment. I've fixed it.

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Nearly there @springstone can you also update this page with your changes: https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Deprecated-Services#deprecated-policies

Thanks

**Comment by Springstone** [comment]
Updated Deprecated Services.

**Review by jtracey93 — DISMISSED** [review]

**Pull request merged**
