### PR TITLE
Enable Defender For Cosmos DB SKU to fix #1081

### LINKED ISSUE #1081: "Configure Microsoft Defender for Azure Cosmos DB to be enabled" Built In Policy Does Not Exist In "Deploy Microsoft Defender for Cloud configuration" Initiative
I notice that "Configure Microsoft Defender for Azure Cosmos DB to be enabled" built in policy does not exist in the "Deploy Microsoft Defender for Cloud configuration" initiative. It's the only one missing. Shouldn't it be added?

/providers/Microsoft.Authorization/policyDefinitions/82bf5b87-728b-4a74-ba4d-6123845cf542

### PR DESCRIPTION
**Pull request by dburlinson**
## Overview/Summary

Enables Microsoft Defender for Azure Cosmos DB to fix https://github.com/Azure/Enterprise-Scale/issues/1081.

## This PR fixes/adds/changes/removes

1. Fixes https://github.com/Azure/Enterprise-Scale/issues/1081

### Breaking Changes

None

## Testing Evidence

[Deploy To Azure](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fdburlinson%2FEnterprise-Scale%2F1081%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fdburlinson%2FEnterprise-Scale%2F1081%2FeslzArm%2Feslz-portal.json)

Screenshots below

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by dburlinson** [comment]
198218451-d4bcd34e-b1cd-4f9c-a782-f26edf1e7cff

**Comment by dburlinson** [comment]
198218876-c2b0a8fa-8722-431c-9819-fc54a9f49b88

**Comment by jtracey93** [comment]
To do:
- [ ] Update assignment
- [ ] Update portal experience

**Review by jtracey93 — APPROVED** [review]
LGTM

**Pull request merged**
