### PR TITLE
Add KV Guardrails Assignment to Platform Management group

### PR DESCRIPTION
**Pull request by Springstone**
## Overview/Summary

The Key Vault Guardrails initiative was previously only assigned to the Landing Zones Management Group. This PR adds the assignment to the Platform Management Group as well. 

## This PR fixes/adds/changes/removes

1. Adds additional assignment of [Enforce-Guardrails-KeyVault](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/Enforce-Guardrails-KeyVault.html) to the Platform Management Group.
2. Updated Portal Reference Implementation to include option under "Platform Management" for Key Vault Guardrails initiative assignment.

### Breaking Changes

1. N/A

## Testing Evidence

image

Portal Update:
image

### Testing URLs

The below URLs can be updated where the placeholders are, look for `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}` & `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}`, to allow you to test your portal deployment experience.

> Please also replace the curly brackets on the placeholders `{}`

#### Azure Public

[Deploy To Azure](https://portal.azure.com/#view/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FSpringstone%2FEnterprise-Scale%2FAddKVAssignment%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FSpringstone%2FEnterprise-Scale%2FAddKVAssignment%2FeslzArm%2Feslz-portal.json)

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [X] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [X] Performed testing and provided evidence.
- [X] Ensured [contribution guidance](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide) is followed.
- [X] Updated relevant and associated documentation.
- [X] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Please add to https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies

**Comment by jtracey93** [comment]
@Springstone do we need to make portal UX changes here also?

**Comment by Springstone** [comment]
> @Springstone do we need to make portal UX changes here also?

That's a good question, I was just piggy backing on Landing Zone, but it would be better to have an option under the Platform section as well.

**Comment by Springstone** [comment]
@jtracey93 I've added a new section and the KV option to the Platform blade of the Portal RI - screenshot in the PR description.

**Review by jtracey93 — APPROVED** [review]

**Pull request merged**
