### PR TITLE
Update Microsoft Defender for Cloud plan for Containers

### PR DESCRIPTION
**Pull request by jtracey93**
## Overview/Summary

As described in issue #874, Microsoft Defender for Cloud has released a new plan to all clouds (Public, Gov, China) for Containers that replaces the plans for Kubernetes & Container Registries.

This has now gone GA as per the announcement here: https://docs.microsoft.com/azure/defender-for-cloud/release-notes#microsoft-defender-for-containers-plan-released-for-general-availability-ga.

## This PR fixes/adds/changes/removes

1. Updates `Deploy-ASCDF-Config` initiative to use the new plan and policy and removed the Kubernetes & Container Registry plan/policies from the initiative, as shown in the below table:

| Policy Definition Display Name | Policy Definition ID | Note |
| ------- | -- | ----- |
| [Deprecated]: Configure Azure Defender for container registries to be enabled | d3d1e68e-49d4-4b56-acff-93cef644b432 | REMOVED - Old ACR policy |
| [Deprecated]: Configure Azure Defender for Kubernetes to be enabled | 133047bf-1369-41e3-a3be-74a11ed1395a | REMOVED - Old AKS Policy |
| Configure Microsoft Defender for Containers to be enabled | c9ddb292-b203-4738-aead-18e2716e858f | ADDED - New grouped containers policy for the new plan |

  - Also added to China (Mooncake) and Gov (Fairfax) policies and deployment experiences, as shown as available here in all 3 clouds: https://docs.microsoft.com/azure/defender-for-cloud/defender-for-containers-introduction?tabs=defender-for-container-arch-aks#availability

2. Update all references of "Azure Defender" in portal experiences to "Microsoft Defender for Cloud"

### Breaking Changes

None. However, customers should review the guidance here around the plan changes and what it means for existing subscriptions and new subscriptions: https://docs.microsoft.com/azure/defender-for-cloud/release-notes#microsoft-defender-for-containers-plan-released-for-general-availability-ga

### Public (Commercial)

**URL to test yourself:** https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fjtracey93%2FEnterprise-Scale%2Ffix-874-mdfc-containers%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fjtracey93%2FEnterprise-Scale%2Ffix-874-mdfc-containers%2FeslzArm%2Feslz-portal.json

image

image

image

image

image

image

### China (Mooncake)

Tested here by @faister https://github.com/Azure/Enterprise-Scale/pull/876#issuecomment-994310822

### Gov (Fairfax)

Tested by @rspott (thanks 👍)
MicrosoftTeams-image

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by jtracey93** [comment]
@faister Could you perform the testing here for China (Mooncake)? I have updated the guidance and all the code so should just need deploying and testing 👍 Can all be found in my fork/branch here: https://github.com/jtracey93/Enterprise-Scale/tree/fix-874-mdfc-containers

Let me know 👍

**Review by amanjeetsingh — COMMENTED** [review]
LGTM!

**Comment by faister** [comment]
> @faister Could you perform the testing here for China (Mooncake)? I have updated the guidance and all the code so should just need deploying and testing 👍 Can all be found in my fork/branch here: https://github.com/jtracey93/Enterprise-Scale/tree/fix-874-mdfc-containers
> 
> Let me know 👍

@jtracey93  Sounds good, will try to get some testing done before we speak mid-week. Trying to finish off the other task I told you about.

**Comment by jtracey93** [comment]
> > @faister
> >             
> >             Fai Lai
> >             FTE Could you perform the testing here for China (Mooncake)? I have updated the guidance and all the code so should just need deploying and testing 👍 Can all be found in my fork/branch here: https://github.com/jtracey93/Enterprise-Scale/tree/fix-874-mdfc-containers
> > Let me know 👍
> 
> @jtracey93 Jack Tracey FTE Sounds good, will try to get some testing done before we speak mid-week. Trying to finish off the other task I told you about.

Thanks @faister, this should also fit into that other piece of work nicely 👍 If you can test before mid-week (just need the definitions and assignments tested really, confirming the new built-in definition `c9ddb292-b203-4738-aead-18e2716e858f` does indeed exist in China (Mooncake) before we merge this PR 👍

**Comment by faister** [comment]
> > > @faister
> > >             
> > >             Fai Lai
> > >             FTE
> > > ```
> > >         Fai Lai
> > >         FTE Could you perform the testing here for China (Mooncake)? I have updated the guidance and all the code so should just need deploying and testing 👍 Can all be found in my fork/branch here: https://github.com/jtracey93/Enterprise-Scale/tree/fix-874-mdfc-containers
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Let me know 👍
> > 
> > 
> > @jtracey93
> >             
> >             Jack Tracey
> >             FTE Jack Tracey FTE Sounds good, will try to get some testing done before we speak mid-week. Trying to finish off the other task I told you about.
> 
> Thanks @faister Fai Lai FTE, this should also fit into that other piece of work nicely 👍 If you can test before mid-week (just need the definitions and assignments tested really, confirming the new built-in definition `c9ddb292-b203-4738-aead-18e2716e858f` does indeed exist in China (Mooncake) before we merge this PR 👍

@jtracey93 All good! The new built-in definition `c9ddb292-b203-4738-aead-18e2716e858f` exists in Mooncake.
Testing evidence:

image

Policy set definition
image

Policy assignment
image

**Comment by jtracey93** [comment]
@Azure/enterprisescale-vteam @Azure/customer-architecture-team - This is now ready for review/approval as testing in all 3 clouds has been completed and attached as evidence above 👍👍

**Review by matt-FFFFFF — DISMISSED** [review]
LGTM - good work @jtracey93

**Review by matt-FFFFFF — APPROVED** [review]
:shipit:

**Pull request merged**
