### PR TITLE
Add Bicep support to `Alz.Tools`

### PR DESCRIPTION
**Pull request by krowlandson**
## Overview/Summary

Updates the `Alz.Tools` PowerShell module to provide support for converting resource templates to format needed for the Bicep repository.

## This PR fixes/adds/changes/removes

1. Add Bicep support to `Alz.Tools`

### Breaking Changes

n/a

## Testing Evidence

Please see output of https://github.com/JamJarchitect/ALZ-Bicep/pull/10/files

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by JamJarchitect** [comment]
Policy definitions are still escaping:

image

However policy set definitions are not being escaped now and are remaining as-is:

image

Need to work with @krowlandson to remove additional escaping in policy definitions to close

**Comment by JamJarchitect** [comment]
New testing evidence shows that policy definitions are no longer escaped and policy initiatives are not escaping either. 

Continuing with PR review in the morning.

**Comment by krowlandson** [comment]
Logic updated to differentiate between policies and initiatives to ensure correct handling of escaping.

Evidence in new PR: https://github.com/JamJarchitect/ALZ-Bicep/pull/11/files

Awaiting sign-off from @JamJarchitect 👍🏻

**Review by JamJarchitect — APPROVED** [review]
LGTM

**Review by jtracey93 — APPROVED** [review]
LGTM

**Pull request merged**
