### PR TITLE
Added Data Policies File

### PR DESCRIPTION
**Pull request by marvinbuss**
## Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. Add data policies json file
2. Removed data policies from policies.json
3. Updated Machine Learning Policy for cross-tenant private endpoints
4. Removed old databricks policies
5. Added Databricks policies to dataPolicies.json

### Breaking Changes

1. None

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [x] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by jtracey93** [comment]
@marvinbuss is this still a work in progress PR?

Also the `dataPolicies.json` file is this going to be the way ESLZ Data/AI policies are handled going forward but still deployed as part of the main Azure Landing Zone Accelerator button expereince?

**Comment by marvinbuss** [comment]
@jtracey93 We will use dataPolicies.json for all data policies. the policies.json is shrinking every month as they are all moving to built-ins. Same is planned for data related policies.

**Comment by jtracey93** [comment]
Awesome. Thanks for the info 😃 

As always, please keep the "Whats New?" page up-to-date 👍

**Comment by marvinbuss** [comment]
@jtracey93 We will do this once we have completed the work.

**Review by krnese — APPROVED** [review]

**Pull request merged**
