### PR TITLE
Adventureworks policies deny vNet peering not working cause of wrong policy mode

### PR DESCRIPTION
**Pull request by marenskoetter**
Policy mode need to be all instead of indexed. Because Microsoft.Network/virtualNetworks/virtualNetworkPeerings does not have location or tag, therefore indexed can't be used.

**This PR fixes**
https://github.com/Azure/Enterprise-Scale/issues/583

### CODE REVIEW

**Review by krnese — CHANGES_REQUESTED** [review]
Many thanks for submitting this PR. Can you also pls make the same changes for the policies.json across Contoso, Wingtip, and Trey Research?

**Comment by marenskoetter** [comment]
Yes, of course I do

**Comment by daltondhcp** [comment]
@marenskoetter - do you have an ETA on the update?

**Comment by daltondhcp** [comment]
Superseded by #649

**Pull request closed without merging**
