### PR TITLE
Deploy Azure Firewall Manager Premium SKU if Premium SKU selected for AZ FW in Hub & Spoke model

### LINKED ISSUE #889: Azure Firewall Policy tier is Standard when using Azure Firewall Premium SKU
If you select premium for firewallSku when deploying a 'Hub and spoke with Azure Firewall' architecture, the deployed Azure Firewall Policy tier is configured as Standard instead of Premium.

### PR DESCRIPTION
**Pull request by jtracey93**
## Overview/Summary

Deploy Azure Firewall Manager Premium SKU if Premium SKU selected for AZ FW in Hub & Spoke model

## This PR fixes/adds/changes/removes

1. Fixes #889 

### Breaking Changes

None

### Public
**URL:** https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fjtracey93%2FEnterprise-Scale%2Ffix-889-fw-pol-sku%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fjtracey93%2FEnterprise-Scale%2Ffix-889-fw-pol-sku%2FeslzArm%2Feslz-portal.json

**Evidence:** 

image

image

image

### US Gov (Fairfax)
**URL:** https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fjtracey93%2FEnterprise-Scale%2Ffix-889-fw-pol-sku%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fjtracey93%2FEnterprise-Scale%2Ffix-889-fw-pol-sku%2FeslzArm%2Ffairfaxeslz-portal.json

**Evidence:** https://github.com/Azure/Enterprise-Scale/pull/890#issuecomment-1040737122

### China (Mooncake)

**Evidence:** https://github.com/Azure/Enterprise-Scale/pull/890#issuecomment-1038983313

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [ ] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by jtracey93** [comment]
@faister & @rspott are you okay to test this one for Mooncake & Fairfax respectively.

Just deploying a premium FW policy and ensure it associates to the AZ FW correctly

**Comment by faister** [comment]
> Sorry to chase @faister & @rspott are you okay to test this one for Mooncake & Fairfax respectively.
> 
> Just deploying a premium FW policy and ensure it associates to the AZ FW correctly from the ALZ portal experience

Sure @jtracey93 . I'll spend some time on this come Monday. But there's no ALZ portal experience on Mooncake though,  will test the template deployment

**Comment by faister** [comment]
China (Mooncake)
Testing steps: No Azure China portal experience for deploying ESLZ hub-spoke networking with AZFW. Executed Azure PowerShell below:
image

Evidence: 
DeploymentName          : EslzMC-hubspoke
Location                : chinaeast2
ProvisioningState       : Succeeded
Timestamp               : 14/02/2022 11:34:13 AM
Mode                    : Incremental

image

**Comment by rspott** [comment]
Reviewed deployment to Fairfax. Deployment was successful.

image

image

**Review by krowlandson — APPROVED** [review]

**Pull request merged**
