### PR TITLE
Update Adventure Works RI Networking Information

### PR DESCRIPTION
**Pull request by jtracey93**
**This PR fixes**

- The 2nd part of issue #573

### CODE REVIEW

**Review by victorar — CHANGES_REQUESTED** [review]
Thanks for the contribution Jack. There is no need to explain how hub and spoke works as that's already documented in multiple other Microsoft articles. 

Instead of that, please just add a small diagram for a hub and spoke architecture, such as figure 2 on this article: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/traditional-azure-networking-topology

And mention that spokes use shared resources in the hub such as ExpressRoute and/or VPN GW, and that transit routing across spokes is achieved by VNet peering, UDR and transit via NVA.

**Comment by jtracey93** [comment]
Thanks @victorar. Have removed the traffic flow section and included links to all the relevant docs.

Have left the new additional diagram as I think this really helps explain and portray how the networking architecture fits with the Management Groups & Subscription organisation in the wider context of Enterprise Scale 👍

**Review by victorar — CHANGES_REQUESTED** [review]
Thanks for your contributions, Jack.

There is no need for a dedicated section for hub and spoke network topology in this article. Instead, within the introduction or customer profile section, just provide a short blurb of what a hub and spoke network topology is, and provide a simple/generic diagram of a hub and spoke network such as the one I shared previously. Then, you can add a link for further details, as well as design considerations and recommendations for hub and spoke networks in ESLZ: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/traditional-azure-networking-topology

**Comment by jtracey93** [comment]
Hey Victor, no problem. 

Have made further updates.

**Review by victorar — COMMENTED** [review]
I made some updates in your fork/branch. Let me know what you think :)

**Review by jtracey93 — COMMENTED** [review]
All good with me 👍

**Review by victorar — APPROVED** [review]

**Pull request merged**
