### PR TITLE
Add profile name parameter to diag policies

### PR DESCRIPTION
**Pull request by anwather**
<h2 id=overviewsummary>Overview/Summary </h2>
<p>Replace this with a brief description of what this Pull Request fixes, changes, etc. </p>
<h2 id=thisprfixesaddschangesremoves>This PR fixes/adds/changes/removes </h2>
<ol>
<li>Updated diagnostic policies where &quot;setByPolicy&quot; is hardcoded as the extension resource in the DINE effect. </li>
</ol>
<p>IHAC where they have deployed the diag policies with a different profile name as a parameter and several resources are reporting as non-compliant because it is looking for a diagnosticSettings/setByPolicy resource. </p>
<p>Remediation works successfully however policy continues to show as non-compliant. </p>
<h3 id=breakingchanges>Breaking Changes </h3>
<p>None </p>
<h2 id=testingevidence>Testing Evidence </h2>
<p>Non compliant resource diagnostics became compliant after this fix. </p>
<h2 id=aspartofthispullrequestihave>As part of this Pull Request I have </h2>
<ul>
<li>[x] Checked for duplicate <a href="https://github.com/Azure/Enterprise-Scale/pulls">Pull Requests</a> </li>
<li>[ ] Associated it with relevant <a href="https://github.com/Azure/Enterprise-Scale/issues">issues</a>, for tracking and closure. </li>
<li>[x] Ensured my code/branch is up-to-date with the latest changes in the <code>main</code> <a href="https://github.com/Azure/Enterprise-Scale/tree/main">branch</a> </li>
<li>[x] Performed testing and provided evidence. </li>
<li>[ ] Updated relevant and associated documentation. </li>
<li>[ ] Updated the <a href="https://github.com/Azure/Enterprise-Scale/wiki/Whats-new">&quot;What's New?&quot;</a> wiki page (located: <code>/docs/wiki/whats-new.md</code>) </li>
</ul>

### CODE REVIEW

**Comment by anwather** [comment]
#1060

**Review by jfaurskov — CHANGES_REQUESTED** [review]
Thank you for your contribution @anwather, great work! Just a couple of minor details if you don't mind.
1. Please assign a default value (SetByPolicy) for the profileName parameter or this will be a breaking change.
2. Please remember to update the version in policy meta data. We are following [this](https://github.com/Azure/azure-policy/blob/master/built-in-policies/README.md#versioning) for versioning 
3. Please also update the associated policy set definition (Deploy-Diagnostics-LogAnalytics.) with the appropriate parameter and default parameters, including parameter assignment for all child policies

**Comment by krowlandson** [comment]
Thank you for your contribution @anwather

When you created this PR did you leave the permissions enabled for [Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

Just trying to work out why the [Update Portal Experience](https://github.com/Azure/Enterprise-Scale/actions/runs/3145224018/jobs/5112238837#step:9:170) action failed with a permissions error.

Putting the feedback from @jfaurskov aside, we will also need this to run successfully before we can merge the PR.

**Comment by cloudchristoph** [comment]
Are you sure about the double opening square brackets?

**Comment by jtracey93** [comment]
> Are you sure about the double opening square brackets?

100% 🤓

This is due to the way the policies get wrapped in variables and then looped over in the resulting compiled `policies.json` file. 

If you werent wrapping them, then yes the escaping isnt the same 👍

**Comment by krowlandson** [comment]
> Are you sure about the double opening square brackets?

@jtracey93 is it worth us running a spike to see whether we can remove these without introducing too much additional complexity into the Bicep template?

We might be able to find a better balance between how I built this vs. the way you handle this in the [ALZ/Bicep](https://aka.ms/alz/bicep) implementation?

**Comment by anwather** [comment]
@jfaurskov - all those policies have a default value for profileName parameter - I have bumped all the versions up. Unless there is something I have missed?

**Comment by anwather** [comment]
> Thank you for your contribution @anwather
> 
> When you created this PR did you leave the permissions enabled for [Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?
> 
> Just trying to work out why the [Update Portal Experience](https://github.com/Azure/Enterprise-Scale/actions/runs/3145224018/jobs/5112238837#step:9:170) action failed with a permissions error.
> 
> Putting the feedback from @jfaurskov aside, we will also need this to run successfully before we can merge the PR.

Permission is definitely enabled on there

**Comment by jtracey93** [comment]
@jfaurskov & @anwather do we need to update the Policy Set Definition/Initiative with the new parameter and version etc?

**Comment by anwather** [comment]
I didn't change the version as there was no update to the initiative - there is already a default value for profile name in the initiative as well

________________________________

**Review by jfaurskov — DISMISSED** [review]
LGTM

**Comment by krowlandson** [comment]
> Why is it trying to push back to my fork?

@anwather we are using automation to re-build the `policies.json` file from the `src` folder content, so when you update an individual policy file, it will trigger this process and write back into the PR.

I've fixed the `git push` issue but it looks like there's a merge conflict, so I'm just going to manually resolve that and we should be good to go on this one.

**Review by jfaurskov — CHANGES_REQUESTED** [review]
@anwather could you please update versioning in the following files, then we should be set to merge:
src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-WVDAppGroup.json
src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-WVDHostPools.json
src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-WVDWorkspace.json

**Comment by anwather** [comment]
> @anwather could you please update versioning in the following files, then we should be set to merge: src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-WVDAppGroup.json src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-WVDHostPools.json src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-WVDWorkspace.json

Updated

**Review by jfaurskov — COMMENTED** [review]
Looks like it's good to merge

**Pull request merged**
