### PR TITLE
24458 Update ALZ Portal Accelerator with DDoS Std Rename to DDoS Netw…

### PR DESCRIPTION
**Pull request by kausd1**
24458 Update ALZ Portal Accelerator with DDoS Std Rename to DDoS Network Protection

### CODE REVIEW

**Review by krowlandson — DISMISSED** [review]
LGTM

**Comment by krowlandson** [comment]
@kausd1 is this the full extent of what you plan to change in this PR, or does more of the repo (e.g. Wiki docs) need to be updated too? I think I know the answer but just checking before we run through the tests, etc.

**Comment by jtracey93** [comment]
> @kausd1 is this the full extent of what you plan to change in this PR, or does more of the repo (e.g. Wiki docs) need to be updated too? I think I know the answer but just checking before we run through the tests, etc.

To your point @krowlandson i am just about to review but was going to ask that the policies and other bits were also updated here.

@kausd1 if you do a search on the repo for DDoS i would suggest updating everywhere that mentions DDoS Std plan to the new naming

I will add a review in about 30 mins detailing and requesting these changes also :)

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Hey @kausd1,

Thanks for this PR, can you please also update the following docs/files:

- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-DDoSProtection.json
    - Also increment version number in `metadata` to `1.0.1` as per: https://github.com/Azure/azure-policy/blob/master/built-in-policies/README.md#versioning
- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/managementGroupTemplates/policyAssignments/MODIFY-DDoSPolicyAssignment.json
- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/eslzArm.json
- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/subscriptionTemplates/nvahubspoke-connectivity.json
- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/subscriptionTemplates/hubspoke-connectivity.json
- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Deploying-ALZ-BasicSetup.md
- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Deploying-ALZ-VWAN.md
- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Deploying-ALZ-HubAndSpoke.md
- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/What-is-Enterprise-Scale.md
- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Deploying-ALZ.md
- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Deploying-ALZ-Foundation.md
- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/contoso/Readme.md
- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md
- [ ] https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/fairfaxeslz-portal.json
- [ ] Also add a summary of the updates to this section of the "whats new" wiki page: https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Whats-new.md#tooling

Thanks for your efforts here, updating all these files will ensure all the naming of DDoS Standard is replaced

Any questions, let us know

Thanks

Jack

cc: @krowlandson

**Comment by kausd1** [comment]
> Hello @jtracey93 
> 
Done
> 
> - [x] https://github.com/Azure/Enterprise-Scale/blob/main/src/resources/Microsoft.Authorization/policyDefinitions/Deploy-DDoSProtection.json
> - [x] Also increment version number in `metadata` to `1.0.1` as per: https://github.com/Azure/azure-policy/blob/master/built-in-policies/README.md#versioning
> - [x]  https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/managementGroupTemplates/policyAssignments/MODIFY-DDoSPolicyAssignment.json
> - [x]  https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/eslzArm.json
> - [x]  https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/subscriptionTemplates/nvahubspoke-connectivity.json
> - [x]  https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/subscriptionTemplates/hubspoke-connectivity.json
> - [x]  https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Deploying-ALZ-BasicSetup.md
> - [x]  https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Deploying-ALZ-VWAN.md
> - [x] https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Deploying-ALZ-HubAndSpoke.md
> - [x] https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/What-is-Enterprise-Scale.md
> - [x]  https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Deploying-ALZ.md
> - [x]  https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Deploying-ALZ-Foundation.md
> - [x]  https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/contoso/Readme.md
> - [x]  https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/adventureworks/README.md
> - [x]  https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/fairfaxeslz-portal.json
> - [x]  Also add a summary of the updates to this section of the "whats new" wiki page: https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/Whats-new.md#tooling


> cc: @krowlandson

**Review by jtracey93 — APPROVED** [review]
LGTM, waiting for tests

**Comment by jtracey93** [comment]
thanks @kausd1 merging

**Pull request merged**
