### PR TITLE
Update Deploy-MDFC-Config_20240319 to use the newer defender for CSPM initiative: 72f8cee7-2937-403d-84a1-a4e3e57f3c21

### PR DESCRIPTION
**Pull request by JonasCordsen**
… initiative: 72f8cee7-2937-403d-84a1-a4e3e57f3c21

## Overview/Summary

This PR will replace the policy for enabling and configuring the MDFC configuration via policies
Initiative: [Deploy-MDFC-Config_20240319]()
Policy to be replaced: [Configure Microsoft Defender CSPM to be enabled](https://www.azadvertizer.net/azpolicyadvertizer/689f7782-ef2c-4270-a6d0-7664869076bd.html)
New policy as a replacement [Configure Microsoft Defender CSPM plan](https://www.azadvertizer.net/azpolicyadvertizer/72f8cee7-2937-403d-84a1-a4e3e57f3c21.html)

## This PR fixes/adds/changes/removes

1. Adds the more settings for MDFC with the new policy added to the initiative Azure/Azure-Landing-Zones#1733

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

### Testing URLs

The below URLs can be updated where the placeholders are, look for `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}` & `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}`, to allow you to test your portal deployment experience.

> Please also replace the curly brackets on the placeholders `{}`

#### Azure Public

[Deploy To Azure](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FJonasCordsen%2FJonas_Enterprise-Scale%2Fmain%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FJonasCordsen%2FJonas_Enterprise-Scale%2Fmain%2FeslzArm%2Feslz-portal.json)

#### Azure US Gov (Fairfax)
[Deploy To Azure](https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FJonasCordsen%2FJonas_Enterprise-Scale%2Fmain%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FJonasCordsen%2FJonas_Enterprise-Scale%2Fmain%2FeslzArm%2Ffairfaxeslz-portal.json)

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Ensured [contribution guidance](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide) is followed.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by JonasCordsen** [comment]
@microsoft-github-policy-service agree [company="JonasCordsen"]

**Comment by JonasCordsen** [comment]
@microsoft-github-policy-service agree

**Comment by jtracey93** [comment]
Thanks @JonasCordsen, I will get @Springstone to look at this when he returns next week 👍

**Review by Springstone — APPROVED** [review]
LGTM. Thank you for this great submission.

**Review by Springstone — CHANGES_REQUESTED** [review]
Almost perfect, one minor change please. Can you please increment the PolicySet major version as per this guidance: https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies#versioning

**Comment by JonasCordsen** [comment]
> Almost perfect, one minor change please. Can you please increment the PolicySet major version as per this guidance: https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies#versioning

This has been updated to 2.0.0

**Review by Springstone — APPROVED** [review]
LGTM

**Comment by jtracey93** [comment]
@Springstone did you confirm this is not a breaking change? And this can be upgraded in place without having to remove any assignments of the policy initiative first?

**Comment by Springstone** [comment]
> @Springstone did you confirm this is not a breaking change? And this can be upgraded in place without having to remove any assignments of the policy initiative first?

@jtracey93 Yes, confirmed and tested. It updates the existing initiative and assignment with the new built-in. No re-assignment necessary.

**Comment by Springstone** [comment]
@JonasCordsen many thanks for your contribution. Just FYI, I've retargeted your PR to the `policy-refresh-q1fy25` branch, which helps our downstream users tackle all changes at once.

**Pull request merged**
