### PR TITLE
new policy added to allow peering to approved virtual networks

### PR DESCRIPTION
**Pull request by Dost2010**
## Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. new policy added  to the list of policies to allow peering from list of approved virtual network.

## Testing Evidence
Tested the policy in my local subscription. 

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by jtracey93** [comment]
Thanks @Dost2010 ill pick this up and review in the coming days 👍

**Comment by Dost2010** [comment]
This screen shot is for peering which is not approved.
image

This screens shot is for peering attempt which is in approved list
image

This is policy assignment 
image

image

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Hey @Dost2010,

Thanks for the work here. A few things to change please:

1. Set the indents on your VSCode to: 4 Spaces (as per https://code.visualstudio.com/docs/editor/codebasics#_indentation)
2. Update indents on `policies.json` - <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>F</kbd>
3. Rename the policy from `allow-approved-VNet-Peering` to `Deny-VNet-Peering-To-Non-Approved-VNet`
4. Add the policy to the following other files:
    - China (Mooncake): `eslzArm/managementGroupTemplates/policyDefinitions/china/mcPolicies.json`
    - US Gov (Fairfax): `eslzArm/managementGroupTemplates/policyDefinitions/gov/fairfaxPolicies.json`
5. Update docs:
    - `ESLZ-Policies.md` - `docs/ESLZ-Policies.md`
    - `WhatsNew.md` - `docs/wiki/Whats-new.md`

Once updated I will review again, and we can proceed with more advanced testing 👍

Thanks again, great start here 👍

**Comment by jtracey93** [comment]
@Dost2010 just wondering if you have had a chance to review https://github.com/Azure/Enterprise-Scale/pull/935#pullrequestreview-905555095

**Comment by Dost2010** [comment]
> @Dost2010 just wondering if you have had a chance to review [#935 (review)](https://github.com/Azure/Enterprise-Scale/pull/935#pullrequestreview-905555095), please review change request

**Comment by Dost2010** [comment]
> > @Dost2010 just wondering if you have had a chance to review [#935 (review)](https://github.com/Azure/Enterprise-Scale/pull/935#pullrequestreview-905555095), please review change request

change request is committed. please review

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Hye @Dost2010,

Looks like the changes in `policies.json` for the new policy have now gone missing from this PR?

Can you re-add them?

Thanks

Jack

**Comment by Dost2010** [comment]
while fixing spacing by mistake i removed the policy. Re-Add it again, however i am unable to fix the "diff" of policies.json while using web diff. Please checkout to local repo and compare if you have to.

**Comment by jtracey93** [comment]
Closing as agreed with @Dost2010 as will re-create in new PR

**Pull request closed without merging**
