### PR TITLE
Portal UX - Fix VWAN Address Space & Remove AzFW Subnet For VWAN

### LINKED ISSUE #714: Azure vWAN Bootstrapping suggests /16 hub address range - Reappeared
As per https://github.com/Azure/Enterprise-Scale/issues/440 where this was recently fixed it seems to have reappeared within the bootstrap deployment latest update

### PR DESCRIPTION
**Pull request by jtracey93**
## Overview/Summary

This PR fixes #714 which has re-occurred in the new eslzArm experience. It also removes the AzFw subnet address space from being specified in VWAN deployments, as this is not required. 

## This PR fixes/adds/changes/removes

1. #714 
2. Removes Azure Firewall Subnet from having to be specified when VWAN is selected for network topology, as this is not used or required.

### Breaking Changes

None

#### Hub & Spoke with AzFW

image

image

image

image

image

#### VWAN

image

image

image

image

image

#### Other

Can also be tested via this URL: https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fjtracey93%2FEnterprise-Scale%2Ffix-714%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fjtracey93%2FEnterprise-Scale%2Ffix-714%2FeslzArm%2Feslz-portal.json

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`) - ***not required***

### CODE REVIEW

**Comment by krnese** [comment]
Thanks Jack for submitting this PR. Instead of adding additional parameters to the ARM template(s), let’s solve this in the portal UX extension directly (client side) to default to the address space recommended for VWAN when VWAN option is selected. We can discuss further when back. Should be a minor update :-)

**Review by hjscherer — APPROVED** [review]
tested and LGTM

**Comment by jtracey93** [comment]
Thanks @hjscherer. After speaking with Kristian yesterday. There may be a slicker way to do this and keep the code DRY'er. I'll convert this to draft whilst I make the changes and test before submitting later 👍

**Comment by jtracey93** [comment]
@krnese @hjscherer This should now be good to go 👍 

The `addressPrefix` output now uses a coalesce, I have tested this in the UI definition Sandbox and outputs are as desired when the relevant options are selected 👍

```
"addressPrefix": "[coalesce(steps('esConnectivityGoalState').esAddressHubVWAN, steps('esConnectivityGoalState').esAddressHubHS, '')]",
```

**Review by krnese — APPROVED** [review]

**Pull request merged**
