### PR TITLE
Rename `Deploy-ASCDF-Config` to `Deploy-MDFC-Config`

### LINKED ISSUE #923: Rename `Deploy-ASCDF-Config` to allow `caf-enterprise-scale` Terraform Module to remove breaking change
As detailed here https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/264#issuecomment-1047724867 

Due to policy parameters being removed from `Deploy-ASCDF-Config` as part of the recent MDFC plan changes as detailed here in the ["What's New?" wiki page](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new#policy-1) and PR #876, when trying to update this in the Terraform module the above error is seen.

To avoid a manual/breaking change for all `caf-enterprise-scale` Terraform module users, we should rename the `Deploy-ASCDF-Config` policy to `Deploy-MDFC-Config` to enable a clean removal and creation of a new policy by the Terraform module.

Other implementations like Bicep & ARM do not currently have an option for lifecycle management (aka "evergreen") so the changes will need to be handled by users of these separately by removing the old assignment of  `Deploy-ASCDF-Config` and then creating a new initiative definition for `Deploy-MDFC-Config` (when published) and then re-assigning to the correct scope (`contoso` by default).

### PR DESCRIPTION
**Pull request by jtracey93**
## Overview/Summary

Fixing #923 (see that issue for more detail)

## This PR fixes/adds/changes/removes

1. Fixes #923 

### Breaking Changes

**None**

ARM & Bicep users will need to manually remove the `Deploy-ASCDF-Config` assignment and initiative definition and then deploy the the new `Deploy-MDFC-Config` initiative definition and assign to Intermediate Root Management Group (aka `Contoso`)

## Testing Evidence

**Azure Public:** https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fjtracey93%2FEnterprise-Scale%2Ffix-923-ASCDF-to-MDFC%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fjtracey93%2FEnterprise-Scale%2Ffix-923-ASCDF-to-MDFC%2FeslzArm%2Feslz-portal.json

image

image

image

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Review by krowlandson — CHANGES_REQUESTED** [review]
Given the new name makes this effectively a new policy definition from an Azure perspective, should we reset the version to `1.0.0`?

**Comment by jtracey93** [comment]
> Given the new name makes this effectively a new policy definition from an Azure perspective, should we reset the version to `1.0.0`?

I updated it from `2.1.0` to `3.0.0` as its technically an major update to the same policy.

But I also see your side/logic. 

Happy to go either way, just say 👍

**Review by krowlandson — APPROVED** [review]
LGTM

**Comment by jtracey93** [comment]
> > Given the new name makes this effectively a new policy definition from an Azure perspective, should we reset the version to `1.0.0`?
> 
> I updated it from `2.1.0` to `3.0.0` as its technically an major update to the same policy.
> 
> But I also see your side/logic.
> 
> Happy to go either way, just say 👍

For completeness we agreed on `v3.0.0` for heritage tracking reasons

**Pull request merged**
