### PR TITLE
Update Deny-Subnet-Without-Nsg Policy to Allow Subnet Exclusions

### LINKED ISSUE #456: Excluded subnets for Deny Subnets without NSG
**Describe the bug**
As per [Issue 38](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/38) in the Terraform module, the "Deny Subnets without NSG" policy currently doesn't allow for networks needing subnets for internal services which do not support NSGs, such as `GatewaySubnet`, `AzureFirewallSubnet`, and `AzureFirewallManagementSubnet`.

**Steps to reproduce**

1. Create a virtual network
2. Assign the policy
3. Try to create one of the subnets which do not support NSGs

### PR DESCRIPTION
**Pull request by jtracey93**
**This PR fixes #456.**

- Updated all Reference Implementations
- Updated What's New wiki page
- Updated ESLZ-Policies page

### CODE REVIEW

**Comment by jtracey93** [comment]
Awaiting feedback from Firewall engineering team regarding protection of Azure Firewall Subnets to clarify statement in FAQ here: https://docs.microsoft.com/en-us/azure/firewall/firewall-faq#are-network-security-groups--nsgs--supported-on-the-azurefirewallsubnet

Once known will be good to review and merge

**Comment by jtracey93** [comment]
Have tested myself this morning (still awaiting engineering feedback) and this looks to be protected by the platform.
**AzureFirewallManagementSubnet**:
image

**AzureFirewallSubnet**:
image

I think we are good to proceed here @victorar & @krnese

**Comment by victorar** [comment]
Looks good, @jtracey93 ! Let us know once you get confirmation from engineering.

**Comment by jtracey93** [comment]
This is also the same for the **GatewaySubnet**:
image

@victorar - will do 👍

**Review by victorar — APPROVED** [review]

**Pull request merged**
