### PR TITLE
Converging Trey Research in UX

### PR DESCRIPTION
**Pull request by krnese**
## Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes
* Default to 'No' on Azure Sentinel when single subscription is used for platform
* Default to 'No' on DDoS when single subscription is used for platform
* Default to 'No' on Azure Firewall when single subscription is used for platform, and require explicit opt-in from customer to enable
* Default to 'No' on enable integrated CI/CD for platform devops and automation

### CODE REVIEW

**Comment by fskelly** [comment]
The changes seem to make it easier to navigate now, single and dedicated branch nicely and now easier to explain to customer and allow them to consume in smaller chunks.

**Comment by krnese** [comment]
> Hi Kristian, on a general note, it's exposing a ton of complexity of its "big brother" and we'd like to keep things simpler if possible and get customers to go the primary experience if they indeed want to modify all details of the implementation. We'd really like to hide a few things (noted below) and lower the "knowledge baseline" required to deploy the solution.
> 
> * On Platform management, security & governance:
>   Consider collapsing the solutions to a single toggle? eg, "deploy a set of default solutions".
>   Maybe also consider reviewing the list of included solutions, eg, why SQL and not other services.
>   Default Sentinel to no
> * Platform devops and automation 👍
> * Network topology:
>   Hide or default "Create Private DNS Zones" to no
>   DDoS protection Standard default to No
>   -Landing Zone
>   Preferably hide or default to no:
>   DDoS protection Standard
>   Public Endpoints
>   All AKS related
>   All Databricks related

When selecting single platform subscription, you should see:
* Sentinel is default to No
* Platform DevOps automation default to No
* DDoS is default to No (which also removes it as option on the landing zone configuration)

It's not clear to me why we should hide Public Endpoint policy for corp connected LZ's, or AKS/Databricks as it relates to the application centric and archetype neutral design principle?

**Review by rjfmachado — DISMISSED** [review]
Hi Kristian, we'll go as is, i did not get any more feedback from my team.

**Review by juazasan — APPROVED** [review]
The later update to the PR does not include additional changes to few variations (defaulting to No few settings) made to the full experience that @rjfmachado already reviewed and accepted. No additional comments from my side.

**Comment by krowlandson** [comment]
Closing as no longer relevant

**Pull request closed without merging**
