### PR TITLE
Added AML Policy to Disable Public Network Access

### PR DESCRIPTION
**Pull request by marvinbuss**
## Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. Added AML Policy to Disable Public Network Access

### Breaking Changes

1. None

## Testing Evidence

I deployed the policy successfully and tested it as well.

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Hey @marvinbuss,

Just a few things from my side, in our efforts to improve PR hygiene across all things ESLZ/ALZ:

- [ ] 1. Is there a screenshot or log output we can show for the testing evidence to back-up/prove the statement that it deploys as part of the E2E Deploy To Azure Button experience?
- [ ] 2. Is there evidence for the policy actually having the desired effect also?
- [ ] 3. Is this just a definition upload but not being assigned as part of the E2E Deploy To Azure Button experience?

Thanks 👍

JT

**Comment by marvinbuss** [comment]
@krnese We should also give users the option to assign some of these policies:

### Azure Machine Learning

|Policy Name  |Policy Area  |Description  |
|---------|---------|---------|
| Deny-MachineLearning-PublicNetworkAccess | Network Security | Azure Machine Learning should have disabled public network access. |
| Deny-MachineLearning-Compute-SubnetId | Network Security | Limit allowed VM sizes for Azure Machine Learning compute clusters and compute instances. |
| Deny-MachineLearning-PublicAccessWhenBehindVnet | Network Security | Deny public acces behind vnet to Azure Machine Learning workspace. |
| Deny-MachineLearning-PublicAccessWhenBehindVnet | Encryption | Enforces high business impact Azure Machine Learning workspaces. |

The Policy `Audit-MachineLearning-PrivateEndpointId` should probably be added to a separate Initiative since this is related to https://github.com/Azure/Enterprise-Scale/issues/785

**Comment by marvinbuss** [comment]
> Hey @marvinbuss,
> 
> Just a few things from my side, in our efforts to improve PR hygiene across all things ESLZ/ALZ:
> 
> 1. Is there a screenshot or log output we can show for the testing evidence to back-up/prove the statement that it deploys as part of the E2E Deploy To Azure Button experience?
> 2. Is there evidence for the policy actually having the desired effect also?
> 3. Is this just a definition upload but not being assigned as part of the E2E Deploy To Azure Button experience?
> 
> Thanks 👍
> 
> JT

Feel free to work on more detailed guidelines regarding what you would like to see. Do you want me to paste the output from my terminal?
Do you want me to share portal screenshots?
Also, you wanted to support this effort, so please take an action and add these details to the PR in order to provide evidence to the team.

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Comment by jtracey93** [comment]
> > Hey @marvinbuss,
> > Just a few things from my side, in our efforts to improve PR hygiene across all things ESLZ/ALZ:
> > 
> > 1. Is there a screenshot or log output we can show for the testing evidence to back-up/prove the statement that it deploys as part of the E2E Deploy To Azure Button experience?
> > 2. Is there evidence for the policy actually having the desired effect also?
> > 3. Is this just a definition upload but not being assigned as part of the E2E Deploy To Azure Button experience?
> > 
> > Thanks 👍
> > JT
> 
> Feel free to work on more detailed guidelines regarding what you would like to see.
> 
> Do you want me to paste the output from my terminal?
> Do you want me to share portal screenshots?
> 
> Also, you wanted to support this effort, so please take an action and add these details to the PR in order to provide evidence to the team.

Hey @marvinbuss,

Screenshots would be ace and easiest I think as per the current PR template suggestion: 
image

It's all just to ensure we are showing our customers/partners/consumers of ESLZ that what we provide is tested works as we state and they expect 👍

I will add further updates to this if we think it needs to be clearer?

As for your last point, I'll ping you offline to clarify a few things 👍

Cheers

JT

**Comment by marvinbuss** [comment]
> > > Hey @marvinbuss,
> > > Just a few things from my side, in our efforts to improve PR hygiene across all things ESLZ/ALZ:
> > > 
> > > 1. Is there a screenshot or log output we can show for the testing evidence to back-up/prove the statement that it deploys as part of the E2E Deploy To Azure Button experience?
> > > 2. Is there evidence for the policy actually having the desired effect also?
> > > 3. Is this just a definition upload but not being assigned as part of the E2E Deploy To Azure Button experience?
> > > 
> > > Thanks 👍
> > > JT
> > 
> > 
> > Do you want me to paste the output from my terminal?
> > Do you want me to share portal screenshots?
> 
> Hey @marvinbuss,
> 
> Screenshots would be ace and easiest I think as per the current PR template suggestion:
> image
> 
> It's all just to ensure we are showing our customers/partners/consumers of ESLZ that what we provide is tested works as we state and they expect 👍
> 
> I will add further updates to this if we think it needs to be clearer?
> 
> As for your last point, I'll ping you offline to clarify a few things 👍
> 
> Cheers
> 
> JT

Here is evidence about the policy effect:
image

```json
"info": {
            "policyDefinitionDisplayName": "Deny-MachineLearning-PublicNetworkAccess",
            "evaluationDetails": {
              "evaluatedExpressions": [
                {
                  "result": "True",
                  "expressionKind": "Field",
                  "expression": "type",
                  "path": "type",
                  "expressionValue": "Microsoft.MachineLearningServices/workspaces",
                  "targetValue": "Microsoft.MachineLearningServices/workspaces",
                  "operator": "Equals"
                },
                {
                  "result": "True",
                  "expressionKind": "Field",
                  "expression": "Microsoft.MachineLearningServices/workspaces/publicNetworkAccess",
                  "path": "properties.publicNetworkAccess",
                  "targetValue": "Disabled",
                  "operator": "NotEquals"
                }
              ]
            },
```

**Comment by marvinbuss** [comment]
> Hey @marvinbuss,
> 
> Just a few things from my side, in our efforts to improve PR hygiene across all things ESLZ/ALZ:
> 
> * [ ]  1. Is there a screenshot or log output we can show for the testing evidence to back-up/prove the statement that it deploys as part of the E2E Deploy To Azure Button experience?
> * [x]  2. Is there evidence for the policy actually having the desired effect also?
> * [ ]  3. Is this just a definition upload but not being assigned as part of the E2E Deploy To Azure Button experience?
> 
> Thanks 👍
> 
> JT

Number 3 will be done at a later date.

For the first point, here is the output from the terminal:
image

Please let me know, whether you require more details or other screenshots.

**Comment by jtracey93** [comment]
> > Hey @marvinbuss
> >             
> >             Marvin Buss
> >             FTE,
> > Just a few things from my side, in our efforts to improve PR hygiene across all things ESLZ/ALZ:
> > 
> > * [ ]   1. Is there a screenshot or log output we can show for the testing evidence to back-up/prove the statement that it deploys as part of the E2E Deploy To Azure Button experience?
> > * [x]   2. Is there evidence for the policy actually having the desired effect also?
> > * [ ]   3. Is this just a definition upload but not being assigned as part of the E2E Deploy To Azure Button experience?
> > 
> > Thanks 👍
> > JT
> 
> Number 3 will be done at a later date.
> 
> For the first point, here is the output from the terminal:
> image
> 
> Please let me know, whether you require more details or other screenshots.

As discussed tested on your behalf and `dataPolicies.json` deploys to an MG succesfully:
image

This close point 1 from my review now 👍

Just point 3 left

**Comment by marvinbuss** [comment]
> > > Hey @marvinbuss
> > > ```
> > >         Marvin Buss
> > >         FTE,
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Just a few things from my side, in our efforts to improve PR hygiene across all things ESLZ/ALZ:
> > > 
> > > * [ ]    1. Is there a screenshot or log output we can show for the testing evidence to back-up/prove the statement that it deploys as part of the E2E Deploy To Azure Button experience?
> > > * [x]    2. Is there evidence for the policy actually having the desired effect also?
> > > * [ ]    3. Is this just a definition upload but not being assigned as part of the E2E Deploy To Azure Button experience?
> > > 
> > > Thanks 👍
> > > JT
> > 
> > 
> > Number 3 will be done at a later date.
> > For the first point, here is the output from the terminal:
> > image
> > Please let me know, whether you require more details or other screenshots.
> 
> As discussed tested on your behalf and `dataPolicies.json` deploys to an MG succesfully:
> image
> 
> This close point 1 from my review now 👍
> 
> Just point 3 left as per: [#807 (comment)](https://github.com/Azure/Enterprise-Scale/pull/807#issuecomment-920127927)

Thank @jtracey93 for the help! Great work!

**Review by krnese — APPROVED** [review]

**Comment by jtracey93** [comment]
@marvinbuss was there an outcome/answer to point 3 as to whether we will wait on this PR to add the portal UX and assignments or not. And if so why?

As per your comment on this PR https://github.com/Azure/Enterprise-Scale/pull/807#issuecomment-920127927 ?

**Comment by krnese** [comment]
> @marvinbuss was there an outcome/answer to point 3 as to whether we will wait on this PR to add the portal UX and assignments or not. And if so why?
> 
> As per your comment on this PR [#807 (comment)](https://github.com/Azure/Enterprise-Scale/pull/807#issuecomment-920127927) ?

This is an update to the dataPolicies.json (policyDefinitions) and we do not need to enable assignment in parallel, that will come later.

**Review by jtracey93 — APPROVED** [review]

**Pull request merged**
