### PR TITLE
Issue #672 - Fix SQL Vulnerability Assessment Policy

### PR DESCRIPTION
**Pull request by JamJarchitect**
## Overview/Summary

Fixing the SQL Vulnerability Assessment policy. Multiple emails can be added, but separated by a `;` as the parameter is a string by design. Also added the Storage Account Contributor RBAC for the policy as it leverages keys.

## This PR fixes/adds/changes/removes

1. Relates to issue #672 
2. `Deploy-Sql-vulnerabilityAssessments.json` added the Storage Account Contributor RBAC
3. `Deploy-Sql-vulnerabilityAssessments.json` tested mutiple emails and the policy remediated successfully
4. `Deploy-Sql-vulnerabilityAssessments.json` tested string versus array, it expects string so added additional context to parameter description to provide detailed guidance

### Breaking Changes

1. N/A

## Testing Evidence

image

### Testing URLs

The below URLs can be updated where the placeholders are, look for `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}` & `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}`, to allow you to test your portal deployment experience.

> Please also replace the curly brackets on the placeholders `{}`

#### Azure Public

[Deploy To Azure](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FJamJarchitect%2FEnterprise-Scale%2Ffixissue672%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FJamJarchitect%2FEnterprise-Scale%2Ffixissue672%2FeslzArm%2Feslz-portal.json)

#### Azure US Gov (Fairfax)
[Deploy To Azure](https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FJamJarchitect%2FEnterprise-Scale%2Ffixissue672%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FJamJarchitect%2FEnterprise-Scale%2Ffixissue672%2FeslzArm%2Ffairfaxeslz-portal.json)

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [X] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [X] Performed testing and provided evidence.
- [X] Ensured [contribution guidance](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide) is followed.
- [X] Updated relevant and associated documentation.
- [X] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by JamJarchitect** [comment]
The configuration after remediation and propagation time shows that SQL Vulnerability Assessments are NOT set up even though they are. It still prompts for express setup (preview).

I will be taking this as feedback to PG, but the functionality is there.

**Review by jtracey93 — CHANGES_REQUESTED** [review]
Hey @JamJarchitect, can we update the version on the policy as per: https://github.com/Azure/Enterprise-Scale/blob/main/docs/wiki/ALZ-Policies.md#versioning

**Review by jtracey93 — APPROVED** [review]
LGTM.

@krowlandson you happy with this as you raised the original issue, testing evidence looks good to me :)

**Comment by krowlandson** [comment]
Great stuff @JamJarchitect... I don't think anyone who looked at this previously had considered that it should genuinely be a list of values within a string! Do we have evidence that the policy now behaves as expected when assigned with a list of email addresses as described in the updated description?

**Comment by JamJarchitect** [comment]
> Great stuff @JamJarchitect... I don't think anyone who looked at this previously had considered that it should genuinely be a list of values within a string! Do we have evidence that the policy now behaves as expected when assigned with a list of email addresses as described in the updated description?

I got the vulnerability reports to both my work email and a personal email by using this policy in the formatted way (email1@contoso.com;email2@fabrikam.com) which worked fine. I could take a screenshot of the emails I receive, the body of the emails is the testing evidence above

I do have some feedback to take to PG which I'll do regarding this per comment above, but all in all it works as expecpted!

**Review by krowlandson — APPROVED** [review]

**Comment by krowlandson** [comment]
Just looking at pulling this into the TF module and was wondering whether we should update the corresponding descriptions on the `Deploy-MDFC-Config` policy set definition, and `Deploy-MDFC-Config` policy assignment?

cc: @JamJarchitect, @jtracey93

**Pull request merged**
