### PR TITLE
Add partialdiscovery environment variable to the Github workflows

### PR DESCRIPTION
**Pull request by hjscherer**

### CODE REVIEW

**Review by uday31in — CHANGES_REQUESTED** [review]
AZOPS_PARTIAL_MG_DISCOVERY_ROOT is not required AFAIK

**Comment by hjscherer** [comment]
@daltondhcp can you confirm?

**Comment by ManuInNZ** [comment]
As a provider inside a big tenancy, can I not use the same approach but
using it against a part of the management group tree/section?
At least that was my understanding of partial.

**Comment by daltondhcp** [comment]
> @daltondhcp can you confirm?

It is not required for partial discovery. If not manually provided it will instead discover based on RBAC permissions. If provided it will obviously honor the input :-)

**Comment by uday31in** [comment]
please add AZOPS_SUPPORT_PARTIAL_MG_DISCOVERY in yaml

**Review by uday31in — APPROVED** [review]

**Pull request merged**
