### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chrisking81**
wrong parameter in the section to Assign Azure Policy to enforce VM Backup on VMs on the landing zones management group.

## Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

### CODE REVIEW

**Comment by jtracey93** [comment]
Keen to close this out @krnese. Any thoughts on my above comment around making this more unique?

Whilst I see your recent commits would resolve this I wonder if we should use this as a chance to step back and review this further?

Happy to chat further to get this closed out 👍

**Comment by krnese** [comment]
> Keen to close this out @krnese. Any thoughts on my above comment around making this more unique?
> 
> Whilst I see your recent commits would resolve this I wonder if we should use this as a chance to step back and review this further?
> 
> Happy to chat further to get this closed out 👍

I think we are good for now with the explicit naming in the DIY guidance given that management group names are not unique within its own tenant, hence does not provide more uniqueness nor ensure a better deterministic approach to tackle the problem that is already solved for.

**Comment by jtracey93** [comment]
> > Keen to close this out @krnese. Any thoughts on my above comment around making this more unique?
> 
> > 
> 
> > Whilst I see your recent commits would resolve this I wonder if we should use this as a chance to step back and review this further?
> 
> > 
> 
> > Happy to chat further to get this closed out 👍
> 
> 
> 
> I think we are good for now with the explicit naming in the DIY guidance given that management group names are not unique within its own tenant, hence does not provide more uniqueness nor ensure a better deterministic approach to tackle the problem that is already solved for.

Hey for clarity where I have got `managementGroup().name` this actually just returns the ID (it's the whole management group ID vs Name thing😁) so in this case it would be unique within the tenant. 

image

Does this change things?

**Comment by krnese** [comment]
The management group id will not be unique (you can have multiple management groups with same id to different parents) within the tenant, hence it’s not adding more than what we have today.

**Comment by jtracey93** [comment]
> The management group id will not be unique (you can have multiple management groups with same id to different parents) within the tenant, hence it’s not adding more than what we have today.

As discussed offline. Management Group IDs are unique, as per: 
image

From: https://docs.microsoft.com/en-us/azure/governance/management-groups/create-management-group-portal#create-in-portal 

However, we agreed we will log a separate issue to track this potential investment in further uniqueness.

**Review by jtracey93 — APPROVED** [review]
Approved and #851 logged to track further enhancements in this area

**Pull request merged**
